spring.application.name=agenda_cultural_servidor

spring.datasource.url= jdbc:postgresql://127.0.0.1:5432/agenda-cultural
spring.datasource.username= agenda-cultural-user
spring.datasource.password= agenda-cultural
