# Geral
spring.application.name= agenda_cultural_servidor

# Banco de dados
spring.datasource.url= jdbc:postgresql://127.0.0.1:5432/agenda-cultural
spring.datasource.username= agenda-cultural-user
spring.datasource.password= agenda-cultural

# Autenticacao JWT
autenticacao.secret_key= U8LmLl83dy9Crx8OcEawljYjL7phJzsC
autenticacao.tempo_validade= 86400000

# Requisicoes
spring.servlet.multipart.max-file-size= 1MB
spring.servlet.multipart.max-request-size= 1MB

# Armazenamento
recursos.diretorio= recursos/
recursos.diretorio.img= recursos/img/