spring.application.name= agenda_cultural_servidor

spring.datasource.url= jdbc:postgresql://127.0.0.1:5432/agenda-cultural
spring.datasource.username= agenda-cultural-user
spring.datasource.password= agenda-cultural

autenticacao.secret_key= U8LmLl83dy9Crx8OcEawljYjL7phJzsC
autenticacao.tempo_validade= 86400000